### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by spikyjt** [Kunstmaan/BootstrapCK4-Skin#6]
It would be really great if this was available as a bower package, so it can be installed with ck using bower.

**Comment by indrikenens** [comment]
That's a fact!
I will make a bower package as soon as there's some spare time at the office.
(i'm guessing in about 3 weeks)

**Comment by mdxs** [comment]
+1

**Comment by nonameolsson** [comment]
This is the full ckeditor with the skin included, right? Not just the skin?
